---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
    requirements-file: requirements.yml
driver:
  name: docker
platforms:
  - name: ubuntu-20.04
    image: srv6d/ubuntu-systemd:20.04
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabilities:
      - SYS_ADMIN
    etc_hosts:
      git.example.com: 127.0.0.1
    privileged: true
    command: "/sbin/init"
    pre_build_image: true
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        gitlab_edition: ${GITLAB_EDITION}
        gitlab_external_url: "https://git.example.com"
        gitlab_registry_external_url: "https://git.example.com:5050"
        gitlab_disable_signup: true
        gitlab_letsencrypt_enable: false
        gitlab_nginx_listen_addresses: ["127.0.0.1"]
        gitlab_nginx_ssl_certificate: /etc/ssl/snakeoil/snakeoil-ecdsa-prime256v1.crt
        gitlab_nginx_ssl_certificate_key: /etc/ssl/snakeoil/snakeoil-ecdsa-prime256v1.key
        gitlab_registry_nginx_listen_addresses: ["127.0.0.1"]
        gitlab_registry_nginx_ssl_certificate: /etc/ssl/snakeoil/snakeoil-ecdsa-prime256v1.crt
        gitlab_registry_nginx_ssl_certificate_key: /etc/ssl/snakeoil/snakeoil-ecdsa-prime256v1.key
        gitlab_root_user_password: "${CI_PIPELINE_ID}${CI_PROJECT_ID}Passw0rd!"
verifier:
  name: testinfra
